### ISSUE TITLE
Artwork resolution does not affect the downloaded cover art

### ISSUE THREAD

**Issue by marcopixel** [RobertFrydenlund/SpotifyPlugin#10]
The measure option `Res` does not affect the artworks resolution, thus downloading the biggest resolution artwork avaliable on Spotify.

Tested on **4.2.0 beta r3064** on **SpotifyPlugin 2.1.4**

**Comment by RobertFrydenlund** [comment]
I am aware of this, the artwork API hasn't been working as expected in quite a while. I will look into it, but i suspect that we will just have to remove the option to specify resolution at all.
