### ISSUE TITLE
seekpercent not working

### ISSUE THREAD

**Issue by jorritsmit** [RobertFrydenlund/SpotifyPlugin#12]
Hi,

when using the following action:

`LeftMouseDownAction=!CommandMeasure "MeasureProgress" "seekpercent 50"`

the position of the song goes to 0% in stead of to 50. Same with seek and setposition. Whatever the argument, the position always goes to the start of the song.

**Comment by IamCarbonMan** [comment]
I'm experiencing this issue as well.
