### ISSUE TITLE
Spotify only showing one artist instead of multiple if avaible.

### ISSUE THREAD

**Issue by ThaumicTom** [RobertFrydenlund/SpotifyPlugin#14]
When multiple artists are shown in Spotify this plugin only shows the very first.

**Comment by RobertFrydenlund** [comment]
This was a limitation of the local API. As we are no longer using it, this issue should be resolved with the [v2.1.6-beta.2](https://github.com/RobertFrydenlund/SpotifyPlugin/releases/tag/v2.1.6-beta.2).
