### ISSUE TITLE
Details on request URL

### ISSUE THREAD

**Issue by mistic100** [RobertFrydenlund/SpotifyPlugin#2]
Hello

I wanted to point out some implementation details that might be useful.

They come from this article http://cgbystrom.com/articles/deconstructing-spotifys-builtin-http-server and this Node module https://www.npmjs.com/package/node-spotify-webhelper

It concerns the URL used to querying the player status :
- the scheme should be HTTPS
- the port can be in the range 4370 to 4380 (depending on which port is available when the helpers starts), 4380 is prefered
- the host should be `[randomString].spotilocal.com`
- you can make requests to `remote/pause.json` (with `pause = true/false` payload) to Pause/Play

Saying that, your hardcoded `http://localhost:4380` seems to work well :-)

**Comment by RobertFrydenlund** [comment]
Tried this for a while, but it seemed to cause more issues than it resolved.
