### ISSUE TITLE
Measures return 0 when Spotify is closed

### ISSUE THREAD

**Issue by MarcoPixel** [RobertFrydenlund/SpotifyPlugin#6]
When Spotify is closed, it will return 0 to Rainmeter. This was not the case before the latest release and i'll assume it's an bug :)

**Log:**
![log screenshot](https://user-images.githubusercontent.com/3743025/33778234-277a30fc-dc48-11e7-8212-c6f10f62ba92.png)

**Skin:**
![skin screenshot](https://user-images.githubusercontent.com/3743025/33778285-495d849e-dc48-11e7-8751-9ce0f7b1df0d.png)

**Comment by RobertFrydenlund** [comment]
Hopefully fixed with da58bc7828de932bf999e158410c906d745d22b5.

**Comment by MarcoPixel** [comment]
@RobertFrydenlund Sound great, thanks for the quick fix.

Just one question, do we have to change anything (skin-wise) to have the new changes? Also i haven't seen a new release of the dll right now, so if you already have built it it would be great to upload it if possibile :)

**Comment by RobertFrydenlund** [comment]
Some features has been removed or changed, so if you are using any of those you might have to update the skin. When i first made this plugin i made some questionable decisions about what values to return (percentages or decimals for example), so hopefully everything is a bit more logical now. If it is not, or there are any other info you want to get, please do not hesitate to open an issue about it. 

I will not release this on the Rainmeter forums yet, as i have given up maintaining the test skin. I would be really happy if you implement the newest version, and let me just link directly to your page instead. (As your skin is my current favorite).
[SpotifyPlugin_2.0.0.zip](https://github.com/RobertFrydenlund/SpotifyPlugin/files/1563480/SpotifyPlugin_2.0.0.zip)

**Comment by MarcoPixel** [comment]
Depends on you, i could make a new example skin to implement it for you if you want or you just can link to one of my skins (as i will update the plugin in all of them as soon as it's ready).

**Comment by RobertFrydenlund** [comment]
I think I will just link to the monstercat skin, as it is my favorite. I tried modifying it myself so spotify could deliver the same functionality the other players can, but it is a little too complicated for me.

**Comment by MarcoPixel** [comment]
Yeah, sometimes its really getting complicated ;) I will check out and modify my skins depending on your changes and i'll hope nothing breaks :)

**Comment by MarcoPixel** [comment]
@RobertFrydenlund I think ArtResolution is broken, it won't change accordingly to the variable set at the measure.

**Comment by RobertFrydenlund** [comment]
@MarcoPixel Did you specifically try 60, 85, 120, 300 or 640? Other values will probably just get a 404 from Spotify's servers. (Already fixing this, but just so i am sure that was the problem)

**Comment by MarcoPixel** [comment]
Yes, i did accordingly to the old sizes specified in the forum post.

**Comment by RobertFrydenlund** [comment]
I'm seriously puzzled about this. At first I was sure that the endpoint just ignored my resolution specifications and returned 640x640, but it isn't consistent at all. I have now found an 639x640 album cover, and one that was 600x600. I do unfortunately think that i just have to change the documentation to "Returns the path to an album cover, usually 640x640, but sometimes a little smaller. (And not necessarily square)"

**Comment by MarcoPixel** [comment]
Okay, it's not that important as the default is big enough to not be pixalated :)

But one bigger issue is that the current position and length of the song are shown as seconds and they were properly encoded as MM:SS before. I would recommend changing this as this would break a lot of skins and might be an issue for especially older skins.

**Comment by MarcoPixel** [comment]
Bangs with !CommandMeasure aren't working here too, so you can't go to the next song or seek to a specific position in the song.

**Comment by RobertFrydenlund** [comment]
I will put the MM:SS back in :)

Are you getting any errors in the rainmeter log when you are using commands? For me `[!CommandMeasure "MeasureProgress" "next"]` works just fine. So does `[!CommandMeasure "MeasureProgress" "seek 100000"]`. `seekpercent` is currently not working unfortunately.

**Comment by MarcoPixel** [comment]
Nope, ``[!CommandMeasure "MeasureProgress" "next"]`` is not working on my system.

**Comment by RobertFrydenlund** [comment]
Try this one, should throw a few more errors.
[SpotifyPlugin_2.0.0.1.zip](https://github.com/RobertFrydenlund/SpotifyPlugin/files/1585170/SpotifyPlugin_2.0.0.1.zip)

**Comment by MarcoPixel** [comment]
Issue fixed on the latest release.
